### ISSUE TITLE
Fixing the bitrot in syscall on crates.io

### ISSUE THREAD

**Issue by urubi** [kmcallister/syscall.rs#12]
Pulling syscall from crates.io gives me the following error when compiling it as a dependency with the latest nightly rust build:

    .../.cargo/registry/src/github.com-1ecc6299db9ec823/syscall-0.1.0/src/lib.rs:18:1 18:11 error: no_std is experimental
    .../.cargo/registry/src/github.com-1ecc6299db9ec823/syscall-0.1.0/src/lib.rs:18 #![no_std]
                                                                                        ^~~~~~~~~~
    ..../.cargo/registry/src/github.com-1ecc6299db9ec823/syscall-0.1.0/src/lib.rs:18:11: 18:11 help: add #![feature(no_std)] to the crate attributes to enable

adding `#![feature(no_std)]` and `#![feature(no_std)]`, and removing `#![allow(unstable)]` made the crate buildable.

**Comment by houqp** [comment]
Got hit by the same problem here.

**Comment by kmcallister** [comment]
Just uploaded the latest as version 0.2.

**Comment by houqp** [comment]
Thank you for the fix :)
