### ISSUE TITLE
linux x64 build failed

### ISSUE THREAD

**Issue by iNode** [kmcallister/syscall.rs#21]
$ cargo build                                                                                      (master)
   Compiling syscall v0.2.0 (file:///home/iNode/devel/rust/tiny-rust-demo/syscall.rs)
src/lib.rs:15:1: 15:25 error: #[feature] may not be used on the stable release channel
src/lib.rs:15 #![feature(asm, no_std)]
              ^~~~~~~~~~~~~~~~~~~~~~~~
error: aborting due to previous error
Could not compile `syscall`.

$ rustc --version
rustc 1.2.0 (082e47636 2015-08-03)

$ uname -m
x86_64

**Comment by kmcallister** [comment]
syscall.rs sort of unavoidably uses inline assembly, so it won't work on the stable branch.
